PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?paper ?title ?year
       (GROUP_CONCAT(DISTINCT ?authorName; separator=" | ") AS ?authors)
WHERE {

  ?paper rdf:type <http://w3id.org/mlso/ScientificWork> .

  OPTIONAL { ?paper dcterms:title ?title }
  OPTIONAL { ?paper dcterms:issued ?year }

  OPTIONAL {
    ?paper dcterms:creator ?author .
    OPTIONAL { ?author foaf:name ?name1 }
    OPTIONAL { ?author rdfs:label ?name2 }
    BIND(COALESCE(?name1, ?name2, STRAFTER(STR(?author), "/")) AS ?authorName)
  }

}
GROUP BY ?paper ?title ?year
LIMIT 50